//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTCCompiler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lexemes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lexemes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTCCompiler.Resources.Lexemes", typeof(Lexemes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AdditionOperator {
            get {
                return ResourceManager.GetString("AdditionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string AndOperator {
            get {
                return ResourceManager.GetString("AndOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :=.
        /// </summary>
        internal static string AssignOperator {
            get {
                return ResourceManager.GetString("AssignOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean.
        /// </summary>
        internal static string BooleanDataType {
            get {
                return ResourceManager.GetString("BooleanDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byref.
        /// </summary>
        internal static string ByRef {
            get {
                return ResourceManager.GetString("ByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byval.
        /// </summary>
        internal static string ByVal {
            get {
                return ResourceManager.GetString("ByVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else.
        /// </summary>
        internal static string ConditionalElse {
            get {
                return ResourceManager.GetString("ConditionalElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-if.
        /// </summary>
        internal static string ConditionalEnd {
            get {
                return ResourceManager.GetString("ConditionalEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if.
        /// </summary>
        internal static string ConditionalIf {
            get {
                return ResourceManager.GetString("ConditionalIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then.
        /// </summary>
        internal static string ConditionalThen {
            get {
                return ResourceManager.GetString("ConditionalThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const.
        /// </summary>
        internal static string ConstDefinition {
            get {
                return ResourceManager.GetString("ConstDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt;.
        /// </summary>
        internal static string DistinctOperator {
            get {
                return ResourceManager.GetString("DistinctOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string DivisionOperator {
            get {
                return ResourceManager.GetString("DivisionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string EndOfInstruction {
            get {
                return ResourceManager.GetString("EndOfInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EqualOperator {
            get {
                return ResourceManager.GetString("EqualOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string FunctionDefinition {
            get {
                return ResourceManager.GetString("FunctionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-func.
        /// </summary>
        internal static string FunctionEnd {
            get {
                return ResourceManager.GetString("FunctionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string GreaterThanOperator {
            get {
                return ResourceManager.GetString("GreaterThanOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string GreaterThanOrEqualOperator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identificador.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string IdTypeSeparator {
            get {
                return ResourceManager.GetString("IdTypeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integer.
        /// </summary>
        internal static string IntegerDataType {
            get {
                return ResourceManager.GetString("IntegerDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expresión entera.
        /// </summary>
        internal static string IntegerExpression {
            get {
                return ResourceManager.GetString("IntegerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        internal static string IterationDo {
            get {
                return ResourceManager.GetString("IterationDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-while.
        /// </summary>
        internal static string IterationEnd {
            get {
                return ResourceManager.GetString("IterationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to while.
        /// </summary>
        internal static string IterationWhile {
            get {
                return ResourceManager.GetString("IterationWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string LeftParenthesis {
            get {
                return ResourceManager.GetString("LeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string LeftSquareBracket {
            get {
                return ResourceManager.GetString("LeftSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string LessThanOperator {
            get {
                return ResourceManager.GetString("LessThanOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string LessThanOrEqualOperator {
            get {
                return ResourceManager.GetString("LessThanOrEqualOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true o false.
        /// </summary>
        internal static string LiteralBoolean {
            get {
                return ResourceManager.GetString("LiteralBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string LiteralFalse {
            get {
                return ResourceManager.GetString("LiteralFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to número.
        /// </summary>
        internal static string LiteralNumber {
            get {
                return ResourceManager.GetString("LiteralNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cadena de caracteres.
        /// </summary>
        internal static string LiteralString {
            get {
                return ResourceManager.GetString("LiteralString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string LiteralTrue {
            get {
                return ResourceManager.GetString("LiteralTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MultiplicationOperator {
            get {
                return ResourceManager.GetString("MultiplicationOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string OrOperator {
            get {
                return ResourceManager.GetString("OrOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procedure.
        /// </summary>
        internal static string ProcedureDefinition {
            get {
                return ResourceManager.GetString("ProcedureDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-proc.
        /// </summary>
        internal static string ProcedureEnd {
            get {
                return ResourceManager.GetString("ProcedureEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string RightParenthesis {
            get {
                return ResourceManager.GetString("RightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string RightSquareBracket {
            get {
                return ResourceManager.GetString("RightSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin.
        /// </summary>
        internal static string ScopeStart {
            get {
                return ResourceManager.GetString("ScopeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SubstractionOperator {
            get {
                return ResourceManager.GetString("SubstractionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        internal static string VariableDefinition {
            get {
                return ResourceManager.GetString("VariableDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showln.
        /// </summary>
        internal static string WriteLine {
            get {
                return ResourceManager.GetString("WriteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xor.
        /// </summary>
        internal static string XorOperator {
            get {
                return ResourceManager.GetString("XorOperator", resourceCulture);
            }
        }
    }
}
