//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTCCompiler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTCCompiler.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se puede declarar un array fuera del entorno global..
        /// </summary>
        internal static string ArrayCantBeDeclaredOutsideGlobalEnvironmentMessage {
            get {
                return ResourceManager.GetString("ArrayCantBeDeclaredOutsideGlobalEnvironmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: En la llamada a &apos;{2}&apos; no se puede pasar un array como parámetro..
        /// </summary>
        internal static string ArrayCantBeSubroutineParameterMessage {
            get {
                return ResourceManager.GetString("ArrayCantBeSubroutineParameterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se puede hacer una asignación a una constante.
        /// </summary>
        internal static string ConstantIsNotAssignableMessage {
            get {
                return ResourceManager.GetString("ConstantIsNotAssignableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: Ya existe un identificador con el nombre &apos;{2}&apos;..
        /// </summary>
        internal static string DuplicateIdentifierFoundMessage {
            get {
                return ResourceManager.GetString("DuplicateIdentifierFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: La expresión no puede ser nula..
        /// </summary>
        internal static string ExpressionIsNullMessage {
            get {
                return ResourceManager.GetString("ExpressionIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se encontró una función con nombre &apos;{2}&apos;..
        /// </summary>
        internal static string FunctionNotFoundMessage {
            get {
                return ResourceManager.GetString("FunctionNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se encontró el identificador &apos;{2}&apos;..
        /// </summary>
        internal static string IdentifierNotFoundMessage {
            get {
                return ResourceManager.GetString("IdentifierNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: El indice de un vector debe ser una expresión entera..
        /// </summary>
        internal static string InvalidArrayIndexMessage {
            get {
                return ResourceManager.GetString("InvalidArrayIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: La expresión no corresponde a un tipo asignable..
        /// </summary>
        internal static string InvalidAssignableTypeMessage {
            get {
                return ResourceManager.GetString("InvalidAssignableTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: Se esperaba una expresión &apos;{2}&apos; y se encontró una del tipo &apos;{3}&apos;..
        /// </summary>
        internal static string InvalidExpressionTypeMessage {
            get {
                return ResourceManager.GetString("InvalidExpressionTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: La cantidad de parametros proporcionados o el tipo de los mismos no coinciden con la definición de &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidParametersCountOrTypeMessage {
            get {
                return ResourceManager.GetString("InvalidParametersCountOrTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: Se esperaba un imprimible y se encontró un &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidPrintableTypeMessage {
            get {
                return ResourceManager.GetString("InvalidPrintableTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEM: El procedimiento MAIN no puede tener un entorno local..
        /// </summary>
        internal static string MainHasLocalEnvironmentMessage {
            get {
                return ResourceManager.GetString("MainHasLocalEnvironmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEM: El procedimiento MAIN no puede tener parámetros..
        /// </summary>
        internal static string MainHasParametersMessage {
            get {
                return ResourceManager.GetString("MainHasParametersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEM: No se encontró el procedimiento MAIN..
        /// </summary>
        internal static string MainNotFoundMessage {
            get {
                return ResourceManager.GetString("MainNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se encontró un procedimiento con nombre &apos;{2}&apos;..
        /// </summary>
        internal static string ProcedureNotFoundMessage {
            get {
                return ResourceManager.GetString("ProcedureNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SEM: No se pueden comparar una expresión de tipo &apos;{2}&apos; con una de tipo &apos;{3}&apos;..
        /// </summary>
        internal static string TypeMismatchMessage {
            get {
                return ResourceManager.GetString("TypeMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}] SIN: Se esperaba {2} y se encontró &apos;{3}&apos;..
        /// </summary>
        internal static string UnexpectedTokenMessage {
            get {
                return ResourceManager.GetString("UnexpectedTokenMessage", resourceCulture);
            }
        }
    }
}
